language: go
matrix:
  include:
    - go: 1.10.x
    - go: tip
  allow_failures:
    - go: tip
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - sourceline: ppa:masterminds/glide
    packages:
    - glide
before_install:
  # setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure
  - rm -fr vendor/github.com/Sirupsen 
  - find vendor -type f -exec sed -i 's/Sirupsen/sirupsen/g' {} +
  - go build
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)
